language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: coverage run --source application runtests.py

after_success: coveralls

env:
  global:
    - SECURE="Q+MhzUQ83n40pBzXCAXThBM/Mi+UqdqtE3j2xv0E3K18kHWHZVXXlhJeeTJq5FhqAzV/JCYHUgJL78PCYlzYiSXt90gN0eTr2inOMMHEwtHfEVdZ7z8CkK7bijpm7HhCRg6DwDSz25SrTcA5vA8aqQZ6ngCssNx85Yiu0Op9OpM="

deploy:
  provider: heroku
  buildpack: python
  api_key: 1c26a711-07cf-47be-a337-c70df8498c75
  app: davidsflask